### PR TITLE
Add version for DLLs; option to create dynamic lib

### PR DESCRIPTION
**Pull request by dirkschulze**
Patch for issues #49 and #51.

### CODE REVIEW

**Comment by dirkschulze** [comment]
@mpsuzuki Could I ask you to take a look at this patch please?

**Comment by mpsuzuki** [comment]
@dirkschulze thanks, should I test this on Windows?

**Comment by dirkschulze** [comment]
@mpsuzuki it is building on Windows. I was thinking of a review 🙂

**Comment by mpsuzuki** [comment]
@dirkschulze OK, please let me spend some time to setup Windows development environment. The wordings VER_FILEVERSION, VER_PRODUCTVERSION are looking slightly odd for me (I think they are MS-specific terms). The versions of DLLs would be same for all platforms (Windows, macOS, and Unixs)?

**Comment by mpsuzuki** [comment]
@dirkschulze Sorry delayed response. I've confirmed that proposed patch makes versioned DLL on Windows well. But during the linking of testSVGNative (the example for the text port), VS complains as they cannot find SVGNativeViewerLib.lib and aborts (please find a line before FAILED error). I would try to find some workarounds.
svg-native-viewer-vsbuild-error

**Comment by dirkschulze** [comment]
@mpsuzuki you see this error because the examples link to SVGNativeViewerLib statically but there is only the dynamic version. You should see a similar problem on other OSs.

**Pull request merged**
